p1=str(input("Digite o nome do primeiro produto "))
p1v=float(input("Digite o valor do primeiro produto "))
p1q=int(input("Digite a quantidade do primeiro produto "))
p2=str(input("Digite o nome do segundo produto "))
p2v=float(input("Digite o valor do segundo produto "))
p2q=int(input("Digite a quantidade do segundo produto "))
p3=str(input("Digite o nome do terceiro produto "))
p3v=float(input("Digite o valor do terceiro produto "))
p3q=int(input("Digite a quantidade do terceiro produto "))
preco=(p1v*p1q)+(p2v*p2q)+(p3v*p3q)
print("o total é de  R$: {}".format(preco))